version: "3"
services:
  reverseproxy:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - 80:8080
    networks:
      - mynetwork
    restart: always

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./Frontend
    depends_on:
      - backend
    networks:
      - mynetwork

  backend:
    build:
      dockerfile: Dockerfile
      context: ./Backend
    networks:
      - mynetwork

networks:
  mynetwork: