version: "3"
services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./Frontend
    ports:
      - "5000:5000"
    depends_on:
      - backend
    networks:
      - mynetwork

  backend:
    build:
      dockerfile: Dockerfile
      context: ./Backend
    ports:
      - "8080:8080"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge