services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./Frontend
    ports:
      - "80:5000"
    networks:
      - private
      - public

  backend:
    build:
      dockerfile: Dockerfile
      context: ./Backend
    ports:
      - "8001:3000"
    networks:
      - private

networks:
  private:
    driver: bridge
  public:
  