name: Review pipeline
run-name: ${{ github.ref_name }} review pipeline

on: [push]

jobs:
  Unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        working-directory: ./Backend
        run: npm install 

      - name: Run tests
        working-directory: ./Backend
        run: npm test

      #- name: Test Reporter
      #  uses: dorny/test-reporter@v1.5.0

  #Test-coverage:
  #  name: Test coverage
   # runs-on: ubuntu-latest
    #steps:
     # # Are next steps needed?
      #- name: Install Node
       # uses: actions/setup-node@v3
        #with:
         # node-version: 16
  #    - name: Checkout
   #     uses: actions/checkout@v3

      # this needs the test suite.
    #  - name: Coveralls GitHub Action
    #    uses: coverallsapp/github-action@1.1.3
     #   with:
      #    github-token: ${{ github.token }}


  Analyze:
      name: Analyze
      runs-on: ubuntu-latest

      strategy:
        fail-fast: false
        matrix:
          language: [ 'javascript' ]

      steps:
        - name: Checkout
          uses: actions/checkout@v3

        # Initializes the CodeQL tools for scanning.
        - name: Initialize CodeQL
          uses: github/codeql-action/init@v2
          with:
            queries: +security-extended
            languages: ${{ matrix.language }}

        - name: Perform CodeQL Analysis
          uses: github/codeql-action/analyze@v2