name: Review pipeline
run-name: ${{ github.ref_name }} review pipeline

on: [push]

jobs:
  Unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Install Node
        uses: actions/setup-node@v1
      - uses: actions/checkout@v1
      - name: Install mocha
        run: npm install -g mocha
      - name: Install dependencies
        run: npm install 

      - name: Run tests
        working-directory: ./Backend/
        run: mocha index.test.js

      #- name: Test report
      #  uses: dorny/test-reporter@v1
      #  if: success() || failure()
      #  with:
      #    name: Mocha Tests
      #    path: reports/*.json
      #    reporter: mocha-json


  Code-scanning:
    name: Code scan
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}

    #- run: |
    #   make bootstrap
    #   make release

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1