name: Review pipeline
run-name: ${{ github.ref_name }} review pipeline

on: [push]

jobs:
  Unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        working-directory: ./Backend
        run: npm install 

      - name: Run tests
        working-directory: ./Backend
        run: npm test
